import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import {Roboto} from "next/font/google";
import { SideBarLayout } from "@/components/authorized/side-bar/SideBar.component";

const roboto = Roboto({weight: ["100", "300", "400", "500", "700", "900"], subsets: ["latin"]});

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <section className={`${geistSans.variable} ${geistMono.variable} antialiased ${roboto.className}`}>
        <SideBarLayout>{children}</SideBarLayout>
      </section>
  );
}
